services:

  db:
    image: postgres:16
    container_name: jkcards-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: jkcards-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./secrets/jwt-private.pem:/run/secrets/jwt-private.pem:ro
      - ./secrets/jwt-public.pem:/run/secrets/jwt-public.pem:ro

    environment:
      SPRING_PROFILES_ACTIVE: prod

      DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}

      JWT_DURATION: ${JWT_DURATION}
      JWT_PRIVATE_KEY_PATH: file:/run/secrets/jwt-private.pem
      JWT_PUBLIC_KEY_PATH: file:/run/secrets/jwt-public.pem

      CORS_ORIGINS: ${CORS_ORIGINS}

      MERCADO_PAGO_ACCESS_TOKEN: ${MERCADO_PAGO_ACCESS_TOKEN}
      APP_FRONTEND_URL: ${APP_FRONTEND_URL}

      MAIL_FROM: ${MAIL_FROM}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_SMTP_AUTH: ${MAIL_SMTP_AUTH}
      MAIL_STARTTLS: ${MAIL_STARTTLS}

      MELHOR_ENVIO_BASE_URL: ${MELHOR_ENVIO_BASE_URL}
      MELHOR_ENVIO_AUTHORIZATION_URL: ${MELHOR_ENVIO_AUTHORIZATION_URL}
      MELHOR_ENVIO_TOKEN_URL: ${MELHOR_ENVIO_TOKEN_URL}
      MELHOR_ENVIO_TOKEN: ${MELHOR_ENVIO_TOKEN}
      MELHOR_ENVIO_ORIGIN_POSTAL_CODE: ${MELHOR_ENVIO_ORIGIN_POSTAL_CODE}
      MELHOR_ENVIO_USER_AGENT: ${MELHOR_ENVIO_USER_AGENT}
      MELHOR_ENVIO_CLIENT_ID: ${MELHOR_ENVIO_CLIENT_ID}
      MELHOR_ENVIO_CLIENT_SECRET: ${MELHOR_ENVIO_CLIENT_SECRET}
      MELHOR_ENVIO_REDIRECT_URI: ${MELHOR_ENVIO_REDIRECT_URI}

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

volumes:
  pgdata: