spring.datasource.url=jdbc:postgresql://localhost:5432/jkcards
spring.datasource.username=postgres
spring.datasource.password=Kauanesophia1#

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

cors.origins=${CORS_ORIGINS}