# =========================
# SERVER
# =========================
server.port=8080

# =========================
# DATABASE
# =========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# =========================
# SECURITY (OAUTH2 CLIENT)
# =========================
security.client-id=myclientid
security.client-secret=myclientsecret
security.jwt.duration=86400

# =========================
# CORS (FRONTEND)
# =========================
cors.origins=http://localhost:3000,http://localhost:5173
# =========================
# CLOUDINARY
# =========================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}