spring.config.import=optional:file:./.env[.properties]

spring.profiles.active=dev

# =========================
# SERVER
# =========================
server.port=8080

# =========================
# SECURITY
# =========================
security.client-id=${SECURITY_CLIENT_ID}
security.client-secret=${SECURITY_CLIENT_SECRET}
security.jwt.duration=${JWT_DURATION:86400}

# =========================
# CLOUDINARY
# =========================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

mercadopago.access-token=${MERCADO_PAGO_ACCESS_TOKEN:}
app.frontend-url=${APP_FRONTEND_URL:http://localhost:5173}

app.mail-from=${MAIL_FROM:no-reply@jkcards.tech}

spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS:true}
spring.mail.properties.mail.smtp.starttls.required=${MAIL_STARTTLS:true}
spring.mail.test-connection=false